android_library(
  name = 'src',
  srcs = glob(['src/main/java/**/*.java']),
  deps = [
    '//libs:gson'
  ],
  visibility = ['PUBLIC'],
  manifest = 'src/main/AndroidManifest.xml',
)

project_config(
  src_target = ':src',
  src_roots = ['src/main/java']
)
